### ISSUE TITLE
Found X and Y gaze points bigger than resolution

### ISSUE THREAD

**Issue by dmsfabiano** [scanavan/GazeEstimation#1]
Example: there is an x value of 268730, for the file: 
./GazeData/tsvData/317s09v1-All-Data.tsv

**Comment by dmsfabiano** [comment]
Should these cases be addressed as OutOfMonitor? or simply just disregard them (what I am doing right now)

**Comment by scanavan** [comment]
Diego,

    These should probably be out of monitor. Seems like it is out of monitor looking the other way.
